apiVersion: v1
kind: Pod

metadata:
  name: my-pod
  labels:
    app: demo
    environment: test
    team: devops

spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
