---
apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - sleep 20; touch /tmp/started; sleep 600
      startupProbe:
        exec:
          command:
          - cat
          - /tmp/started
        periodSeconds: 5
        failureThreshold: 12
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/started
        periodSeconds: 5
